[AGL][build] Declare *viz_fmp_*timeout_ under correct #ifdef
All uses of use_viz_fmp_with_timeout_ and viz_fmp_timeout_
happen under #if defined(USE_NEVA_APPRUNTIME), but they
were declared under #if defined(OS_WEBOSE).

Fixes compilation error when OS_WEBOSE is not defined and
USE_NEVA_APPRUNTIME is.

| ./../../git/src/content/browser/compositor/gpu_process_transport_factory.cc:191:3: error: 'use_viz_fmp_with_timeout_' was n\
ot declared in this scope
|   191 |   use_viz_fmp_with_timeout_ = switches::UseVizFMPWithTimeout();
|       |   ^~~~~~~~~~~~~~~~~~~~~~~~~
| ./../../git/src/content/browser/compositor/gpu_process_transport_factory.cc:192:3: error: 'viz_fmp_timeout_' was not declar\
ed in this scope
|   192 |   viz_fmp_timeout_ = switches::GetVizFMPTimeout();
|       |   ^~~~~~~~~~~~~~~~

Signed-off-by: Antia Puentes <apuentes@igalia.com>