[AGL][build] Declare NotifyVizFMPSwap under correct #ifdef
ALl its uses happen under #if defined(USE_NEVA_APPRUNTIME),
but it was declared under #if defined(OS_WEBOSE).

Fixes compilation error when OS_WEBOSE is not defined and
USE_NEVA_APPRUNTIME is.

| ../../git/src/content/renderer/render_widget.h:495:8: error: 'void content::RenderWidget::NotifyVizFMPSwap(bool, bool)' mar\
ked 'override', but does not override
|   495 |   void NotifyVizFMPSwap(bool is_first_contentful_paint,
|       |        ^~~~~~~~~~~~~~~~

Signed-off-by: Antia Puentes <apuentes@igalia.com>