[AGL][build] Add missing #if defined(OS_WEBOS)
Functions AddCorbExceptionForProcess and RemoveCorbExceptionForProcess
are declared under #if defined(OS_WEBOS) but they were being called
without it.

Fixes compilation errors:

| ../../git/src/neva/app_runtime/browser/app_runtime_content_browser_client.cc:654:26: error: 'class network::mojom::NetworkS\
ervice' has no member named 'AddCorbExceptionForProcess'; did you mean 'AddCorbExceptionForPlugin'?
|   654 |     GetNetworkService()->AddCorbExceptionForProcess(process_id);
|       |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                          AddCorbExceptionForPlugin
| ../../git/src/neva/app_runtime/browser/app_runtime_content_browser_client.cc:656:26: error: 'class network::mojom::NetworkS\
ervice' has no member named 'RemoveCorbExceptionForProcess'; did you mean 'RemoveCorbExceptionForPlugin'?
|   656 |     GetNetworkService()->RemoveCorbExceptionForProcess(process_id);
|       |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                          RemoveCorbExceptionForPlugin

Signed-off-by: Antia Puentes <apuentes@igalia.com>